[workspace]
authors = ["Nicole Kenneth <nicolekenneth214@gmail.com>"]
channels = ["conda-forge"]
name = "BINF-5507-Winter-2026"
platforms = ["win-64", "osx-arm64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<3.14"
numpy = ">=2.4.2,<3"
pandas = ">=3.0.0,<4"
ipykernel = ">=7.2.0,<8"
